import Footer from '@/components/layout/Footer';
import NavBar from '@/components/layout/NavBar';

import './globals.css';

import { lato, noto_serif } from './fonts';

export const metadata = {
  title: 'OA-Next',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${lato.variable} ${noto_serif.variable}`}>
      <body className="my-16">
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
