import { lato, noto_serif } from './fonts';
import './globals.css';

export const metadata = {
  title: 'OA-Next',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${lato.variable} ${noto_serif.variable}`}>
      <body>{children}</body>
    </html>
  );
}
